### ISSUE TITLE
Using short nodepool ID when scaling a nodepool causing an error

### ISSUE THREAD

**Issue by zulh-civo** [civo/cli-go#158]
```
# Scaling
$ civo k8s node-pool scale test 26c6eb --nodes=2
Error: Unable to find "26c6eb" node pool inside "test" cluster

# Deleting
$ civo k8s node-pool delete test 26c6eb
Warning: Are you sure you want to delete the 26c6eb node pool (y/N) ? y
The node pool (26c6eb) has been deleted from the cluster (test)
```

This behaviour is inconsistent with the `civo k8s node-pool delete` command. We should accept both short nodepool ID and full nodepool ID when scaling nodepool — just like the `delete` command.

**Comment by avinashupadhya99** [comment]
Hi, can I work on this if that's alright? Would love to get my hands dirty with the cli

**Comment by zulh-civo** [comment]
Go for it @avinashupadhya99. Thanks for your help.

**Comment by avinashupadhya99** [comment]
The delete command checks for the node pool through `strings.Contains` but I feel like this could end up scaling/deleting the wrong node pool. Here's an example of my node-pools - 
```
94b7099b-3f4d-450e-986f-e8161b7a1572
99b70517-1e39-49f2-a153-35f74a172cc7
```
If I run `civo kubernetes pool delete test-cluster 99b`, it will end up deleting the first node pool but the user might have intended to delete the second node pool based on the first few characters. We should either have a check on the length of the ID provided or check for the match of first few characters of the ID instead of contains. Please let me know your thoughts on this and I can implement it accordingly.

A simple fix for the issue in question now would be use `strings.Contains` while checking for the node pool during scaling but these were my thoughts and observations.

**Comment by zulh-civo** [comment]
I think, we can keep the `strings.Contains` so users can continue scaling/deleting nodepools by full/long ID or part of the ID.

To make it better, let's check the provided nodepool ID length as well. In Civo.com web UI, we are showing 6 characters as "friendly ID" for nodepools. IMHO, 6 characters is sufficient to avoid any collision (as per situation you described above).

![nodepool](https://user-images.githubusercontent.com/75463191/138218246-6504670d-a1b9-4b1f-b8f7-cd2f410c87ee.png)

So, here are the tasks for this issue:

- [ ] When deleting nodepool, keep `strings.Contains` usage. Check the length to be at least 6 characters
- [ ] When scaling nodepool, implement `strings.Contains` and check the length to be at least 6 characters
- [ ] When user provides short nodepool ID (<6), exit the CLI and ask user to provide an ID with at least 6 characters

When user provides a short nodepool ID (e.g. just 6 characters), I think we don't have to check if they are the first 6 characters of the full/long ID (because we are using `strings.Contains`). They can start from the middle if they like. As long as it's at least 6 characters.

**Comment by avinashupadhya99** [comment]
I've done these changes in #160 
I was also wondering if we could display the entire nodepool ID of the nodepool that was scaled in the output for more clarity.
Here's the current output - 
```
The pool (99b705) was scaled to (2) in the cluster (test-cluster)
```
My suggestion - 
```
The pool (99b70517-1e39-49f2-a153-35f74a172cc7) was scaled to (2) in the cluster (test-cluster)
```

**Comment by zulh-civo** [comment]
I launched a cluster and I got this:

```sh
$ civo k8s create test --size=g3.k3s.xsmall --nodes=1
The cluster test (d896e4fe-9cf4-488f-afeb-f0c4e3c9a997) has been created
```

I agree with you, we should show the full/long ID for consistency.

Do you mind updating your PR and ping me / @alejandrojnm when it's ready for review?
